runtime: nodejs20
handlers:
 # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  
  # Serve index.html for all other routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html